-- Enable and force RLS on all tables defined so far
-- Note: enabling RLS without policies will reject access for anon/users.
-- Ensure appropriate policies are added per access requirements.

-- Core entities
ALTER TABLE IF EXISTS users            ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS users            FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS vendors          ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS vendors          FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS categories       ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS categories       FORCE ROW LEVEL SECURITY;

-- Products domain
ALTER TABLE IF EXISTS products         ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS products         FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS product_variants ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS product_variants FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS inventory        ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS inventory        FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS product_images   ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS product_images   FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tags             ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS tags             FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS product_tags     ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS product_tags     FORCE ROW LEVEL SECURITY;

-- Orders domain
ALTER TABLE IF EXISTS orders           ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS orders           FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_items      ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS order_items      FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payments         ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS payments         FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS shipments        ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS shipments        FORCE ROW LEVEL SECURITY;

-- Messaging/notifications
ALTER TABLE IF EXISTS conversations    ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS conversations    FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS messages         ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS messages         FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notifications    ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS notifications    FORCE ROW LEVEL SECURITY;

-- Cart
ALTER TABLE IF EXISTS shopping_carts   ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS shopping_carts   FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS cart_items       ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS cart_items       FORCE ROW LEVEL SECURITY;

-- Reviews
ALTER TABLE IF EXISTS reviews          ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS reviews          FORCE ROW LEVEL SECURITY;

